pipeline {
    agent { label 'java-maven' }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean package -DskipTests -f ecom.application/ecom.application/pom.xml'
            }
        }

        stage('Archive JAR') {
            steps {
                archiveArtifacts artifacts: 'ecom.application/ecom.application/target/*.jar',
                                 fingerprint: true
            }
        }

    }

    post {
        success { echo 'Build successful!' }
        failure { echo 'Build failed!' }
    }
}
